name: Build, Deploy, and Tag

on:
  workflow_dispatch:
    inputs:
      qa-env:
        type: choice
        description: QA environment to deploy to
        required: true
        options:
          - qa-1
          - qa-2
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Message
        run: |
          echo "DO NOT use this with a real secret... this is for demonstration purposes only"
          echo ${{ secrets.MESSAGE }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-build
          path: ./

  qa-1:
    runs-on: ubuntu-latest
    environment: qa-1
    needs: build
    if: ${{ github.event.inputs.qa-env == 'qa-1' }} 

    steps:
      - name: Retrieve Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-build

      - name: Message
        run: |
          echo "DO NOT use this with a real secret... this is for demonstration purposes only"
          echo ${{ secrets.MESSAGE }}

      - name: Deploy
        run: echo "Deploying to qa-1..."

  qa-2:
    runs-on: ubuntu-latest
    environment: qa-2
    needs: build
    if: ${{ github.event.inputs.qa-env == 'qa-2' }} 

    steps:
      - name: Retrieve Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-build

      - name: Message
        run: |
          echo "DO NOT use this with a real secret... this is for demonstration purposes only"
          echo ${{ secrets.MESSAGE }}

      - name: Deploy
        run: echo "Deploying to qa-2..."

  stag:
    runs-on: ubuntu-latest
    environment: stag
    needs: build
    if: ${{ ! contains(github.event.inputs.qa-env, 'qa') }} 

    steps:
      - name: Retrieve Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-build

      - name: Message
        run: |
          echo "DO NOT use this with a real secret... this is for demonstration purposes only"
          echo ${{ secrets.MESSAGE }}

      - name: Check current directory and contents
        run: |
          ls
          pwd

      - name: Bump tag version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: true

      - name: Deploy
        run: echo "Deploying to staging..."

  prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: stag

    steps:
      - name: Retrieve Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-build

      - name: Message
        run: |
          echo "DO NOT use this with a real secret... this is for demonstration purposes only"
          echo ${{ secrets.MESSAGE }}

      - name: Bump tag version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: major
          WITH_V: true

      - name: Deploy
        run: echo "Deploying to production..."
